// Additional problems - Part 4 (problems 31-45)
export default [
  {
    title: "Valid Palindrome",
    description: "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.\n\nGiven a string s, return true if it is a palindrome, or false otherwise.",
    difficulty: "EASY",
    tags: ["Two Pointers", "String"],
    examples: [{ input: '"A man, a plan, a canal: Panama"', output: "true" }],
    constraints: "1 <= s.length <= 2 * 10^5\ns consists only of printable ASCII characters.",
    testCases: [{ input: "A man, a plan, a canal: Panama", output: "true" }, { input: "race a car", output: "false" }],
    codeSnippet: { JAVASCRIPT: "function isPalindrome(s) {\n  // Your code here\n}", PYTHON: "def isPalindrome(s):\n    pass", JAVA: "class Solution {\n    public boolean isPalindrome(String s) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function isPalindrome(s) {\n  s = s.toLowerCase().replace(/[^a-z0-9]/g, '');\n  let left = 0, right = s.length - 1;\n  while (left < right) {\n    if (s[left++] !== s[right--]) return false;\n  }\n  return true;\n}", PYTHON: "def isPalindrome(s):\n    s = ''.join(c.lower() for c in s if c.isalnum())\n    return s == s[::-1]", JAVA: "class Solution {\n    public boolean isPalindrome(String s) {\n        s = s.toLowerCase().replaceAll(\"[^a-z0-9]\", \"\");\n        int left = 0, right = s.length() - 1;\n        while (left < right) {\n            if (s.charAt(left++) != s.charAt(right--)) return false;\n        }\n        return true;\n    }\n}" }
  },
  {
    title: "Valid Sudoku",
    description: "Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:\n\n1. Each row must contain the digits 1-9 without repetition.\n2. Each column must contain the digits 1-9 without repetition.\n3. Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.",
    difficulty: "MEDIUM",
    tags: ["Array", "Hash Table", "Matrix"],
    examples: [{ input: "9x9 board", output: "true" }],
    constraints: "board.length == 9\nboard[i].length == 9\nboard[i][j] is a digit 1-9 or '.'",
    testCases: [{ input: "5,3,.,.,7,.,.,.,.\n6,.,.,1,9,5,.,.,.\n.,9,8,.,.,.,.,6,.\n8,.,.,.,6,.,.,.,3\n4,.,.,8,.,3,.,.,1\n7,.,.,.,2,.,.,.,6\n.,6,.,.,.,.,2,8,.\n.,.,.,4,1,9,.,.,5\n.,.,.,.,8,.,.,7,9", output: "true" }],
    codeSnippet: { JAVASCRIPT: "function isValidSudoku(board) {\n  // Your code here\n}", PYTHON: "def isValidSudoku(board):\n    pass", JAVA: "class Solution {\n    public boolean isValidSudoku(char[][] board) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function isValidSudoku(board) {\n  const rows = Array(9).fill(0).map(() => new Set());\n  const cols = Array(9).fill(0).map(() => new Set());\n  const boxes = Array(9).fill(0).map(() => new Set());\n  for (let r = 0; r < 9; r++) {\n    for (let c = 0; c < 9; c++) {\n      const val = board[r][c];\n      if (val === '.') continue;\n      const boxIdx = Math.floor(r / 3) * 3 + Math.floor(c / 3);\n      if (rows[r].has(val) || cols[c].has(val) || boxes[boxIdx].has(val)) return false;\n      rows[r].add(val); cols[c].add(val); boxes[boxIdx].add(val);\n    }\n  }\n  return true;\n}", PYTHON: "def isValidSudoku(board):\n    rows = [set() for _ in range(9)]\n    cols = [set() for _ in range(9)]\n    boxes = [set() for _ in range(9)]\n    for r in range(9):\n        for c in range(9):\n            val = board[r][c]\n            if val == '.': continue\n            box_idx = (r // 3) * 3 + c // 3\n            if val in rows[r] or val in cols[c] or val in boxes[box_idx]: return False\n            rows[r].add(val); cols[c].add(val); boxes[box_idx].add(val)\n    return True", JAVA: "class Solution {\n    public boolean isValidSudoku(char[][] board) {\n        Set<String> seen = new HashSet<>();\n        for (int r = 0; r < 9; r++) {\n            for (int c = 0; c < 9; c++) {\n                char val = board[r][c];\n                if (val == '.') continue;\n                if (!seen.add(val + \"r\" + r) || !seen.add(val + \"c\" + c) || !seen.add(val + \"b\" + r/3 + c/3)) return false;\n            }\n        }\n        return true;\n    }\n}" }
  },
  {
    title: "Trapping Rain Water",
    description: "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
    difficulty: "HARD",
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack", "Monotonic Stack"],
    examples: [{ input: "[0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" }],
    constraints: "n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5",
    testCases: [{ input: "0,1,0,2,1,0,1,3,2,1,2,1", output: "6" }, { input: "4,2,0,3,2,5", output: "9" }],
    codeSnippet: { JAVASCRIPT: "function trap(height) {\n  // Your code here\n}", PYTHON: "def trap(height):\n    pass", JAVA: "class Solution {\n    public int trap(int[] height) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function trap(height) {\n  let left = 0, right = height.length - 1;\n  let leftMax = 0, rightMax = 0, water = 0;\n  while (left < right) {\n    if (height[left] < height[right]) {\n      leftMax = Math.max(leftMax, height[left]);\n      water += leftMax - height[left++];\n    } else {\n      rightMax = Math.max(rightMax, height[right]);\n      water += rightMax - height[right--];\n    }\n  }\n  return water;\n}", PYTHON: "def trap(height):\n    left, right = 0, len(height) - 1\n    left_max = right_max = water = 0\n    while left < right:\n        if height[left] < height[right]:\n            left_max = max(left_max, height[left])\n            water += left_max - height[left]\n            left += 1\n        else:\n            right_max = max(right_max, height[right])\n            water += right_max - height[right]\n            right -= 1\n    return water", JAVA: "class Solution {\n    public int trap(int[] height) {\n        int left = 0, right = height.length - 1;\n        int leftMax = 0, rightMax = 0, water = 0;\n        while (left < right) {\n            if (height[left] < height[right]) {\n                leftMax = Math.max(leftMax, height[left]);\n                water += leftMax - height[left++];\n            } else {\n                rightMax = Math.max(rightMax, height[right]);\n                water += rightMax - height[right--];\n            }\n        }\n        return water;\n    }\n}" }
  },
  {
    title: "Min Stack",
    description: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.\n\nImplement the MinStack class:\n- MinStack() initializes the stack object.\n- void push(int val) pushes the element val onto the stack.\n- void pop() removes the element on the top of the stack.\n- int top() gets the top element of the stack.\n- int getMin() retrieves the minimum element in the stack.",
    difficulty: "MEDIUM",
    tags: ["Stack", "Design"],
    examples: [{ input: "push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()", output: "-3, 0, -2" }],
    constraints: "-2^31 <= val <= 2^31 - 1\nMethods pop, top and getMin operations will always be called on non-empty stacks.",
    testCases: [{ input: "push,-2;push,0;push,-3;getMin;pop;top;getMin", output: "-3,0,-2" }],
    codeSnippet: { JAVASCRIPT: "class MinStack {\n  constructor() {\n    // Your code here\n  }\n  push(val) {}\n  pop() {}\n  top() {}\n  getMin() {}\n}", PYTHON: "class MinStack:\n    def __init__(self):\n        pass\n    def push(self, val):\n        pass\n    def pop(self):\n        pass\n    def top(self):\n        pass\n    def getMin(self):\n        pass", JAVA: "class MinStack {\n    public MinStack() {\n    }\n    public void push(int val) {\n    }\n    public void pop() {\n    }\n    public int top() {\n    }\n    public int getMin() {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "class MinStack {\n  constructor() {\n    this.stack = [];\n    this.minStack = [];\n  }\n  push(val) {\n    this.stack.push(val);\n    const min = this.minStack.length ? Math.min(val, this.getMin()) : val;\n    this.minStack.push(min);\n  }\n  pop() {\n    this.stack.pop();\n    this.minStack.pop();\n  }\n  top() {\n    return this.stack[this.stack.length - 1];\n  }\n  getMin() {\n    return this.minStack[this.minStack.length - 1];\n  }\n}", PYTHON: "class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []\n    def push(self, val):\n        self.stack.append(val)\n        min_val = min(val, self.min_stack[-1]) if self.min_stack else val\n        self.min_stack.append(min_val)\n    def pop(self):\n        self.stack.pop()\n        self.min_stack.pop()\n    def top(self):\n        return self.stack[-1]\n    def getMin(self):\n        return self.min_stack[-1]", JAVA: "class MinStack {\n    private Stack<Integer> stack = new Stack<>();\n    private Stack<Integer> minStack = new Stack<>();\n    public void push(int val) {\n        stack.push(val);\n        int min = minStack.isEmpty() ? val : Math.min(val, minStack.peek());\n        minStack.push(min);\n    }\n    public void pop() { stack.pop(); minStack.pop(); }\n    public int top() { return stack.peek(); }\n    public int getMin() { return minStack.peek(); }\n}" }
  },
  {
    title: "Evaluate Reverse Polish Notation",
    description: "You are given an array of strings tokens that represents an arithmetic expression in a Reverse Polish Notation.\n\nEvaluate the expression. Return an integer that represents the value of the expression.",
    difficulty: "MEDIUM",
    tags: ["Array", "Math", "Stack"],
    examples: [{ input: '["2","1","+","3","*"]', output: "9", explanation: "((2 + 1) * 3) = 9" }],
    constraints: "1 <= tokens.length <= 10^4\ntokens[i] is either an operator: \"+\", \"-\", \"*\", or \"/\", or an integer",
    testCases: [{ input: "2,1,+,3,*", output: "9" }, { input: "4,13,5,/,+", output: "6" }],
    codeSnippet: { JAVASCRIPT: "function evalRPN(tokens) {\n  // Your code here\n}", PYTHON: "def evalRPN(tokens):\n    pass", JAVA: "class Solution {\n    public int evalRPN(String[] tokens) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function evalRPN(tokens) {\n  const stack = [];\n  for (let t of tokens) {\n    if (['+', '-', '*', '/'].includes(t)) {\n      const b = stack.pop(), a = stack.pop();\n      if (t === '+') stack.push(a + b);\n      else if (t === '-') stack.push(a - b);\n      else if (t === '*') stack.push(a * b);\n      else stack.push(Math.trunc(a / b));\n    } else stack.push(parseInt(t));\n  }\n  return stack[0];\n}", PYTHON: "def evalRPN(tokens):\n    stack = []\n    for t in tokens:\n        if t in '+-*/':\n            b, a = stack.pop(), stack.pop()\n            if t == '+': stack.append(a + b)\n            elif t == '-': stack.append(a - b)\n            elif t == '*': stack.append(a * b)\n            else: stack.append(int(a / b))\n        else: stack.append(int(t))\n    return stack[0]", JAVA: "class Solution {\n    public int evalRPN(String[] tokens) {\n        Stack<Integer> stack = new Stack<>();\n        for (String t : tokens) {\n            if (\"+-*/\".contains(t)) {\n                int b = stack.pop(), a = stack.pop();\n                switch (t) {\n                    case \"+\": stack.push(a + b); break;\n                    case \"-\": stack.push(a - b); break;\n                    case \"*\": stack.push(a * b); break;\n                    case \"/\": stack.push(a / b); break;\n                }\n            } else stack.push(Integer.parseInt(t));\n        }\n        return stack.peek();\n    }\n}" }
  },
  {
    title: "Search in Rotated Sorted Array",
    description: "There is an integer array nums sorted in ascending order (with distinct values).\n\nPrior to being passed to your function, nums is possibly rotated at an unknown pivot index k.\n\nGiven the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.\n\nYou must write an algorithm with O(log n) runtime complexity.",
    difficulty: "MEDIUM",
    tags: ["Array", "Binary Search"],
    examples: [{ input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4" }],
    constraints: "1 <= nums.length <= 5000\n-10^4 <= nums[i] <= 10^4",
    testCases: [{ input: "4,5,6,7,0,1,2\n0", output: "4" }, { input: "4,5,6,7,0,1,2\n3", output: "-1" }],
    codeSnippet: { JAVASCRIPT: "function search(nums, target) {\n  // Your code here\n}", PYTHON: "def search(nums, target):\n    pass", JAVA: "class Solution {\n    public int search(int[] nums, int target) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function search(nums, target) {\n  let left = 0, right = nums.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (nums[mid] === target) return mid;\n    if (nums[left] <= nums[mid]) {\n      if (nums[left] <= target && target < nums[mid]) right = mid - 1;\n      else left = mid + 1;\n    } else {\n      if (nums[mid] < target && target <= nums[right]) left = mid + 1;\n      else right = mid - 1;\n    }\n  }\n  return -1;\n}", PYTHON: "def search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if nums[mid] == target: return mid\n        if nums[left] <= nums[mid]:\n            if nums[left] <= target < nums[mid]: right = mid - 1\n            else: left = mid + 1\n        else:\n            if nums[mid] < target <= nums[right]: left = mid + 1\n            else: right = mid - 1\n    return -1", JAVA: "class Solution {\n    public int search(int[] nums, int target) {\n        int left = 0, right = nums.length - 1;\n        while (left <= right) {\n            int mid = left + (right - left) / 2;\n            if (nums[mid] == target) return mid;\n            if (nums[left] <= nums[mid]) {\n                if (nums[left] <= target && target < nums[mid]) right = mid - 1;\n                else left = mid + 1;\n            } else {\n                if (nums[mid] < target && target <= nums[right]) left = mid + 1;\n                else right = mid - 1;\n            }\n        }\n        return -1;\n    }\n}" }
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    description: "Suppose an array of length n sorted in ascending order is rotated between 1 and n times.\n\nGiven the sorted rotated array nums of unique elements, return the minimum element of this array.\n\nYou must write an algorithm that runs in O(log n) time.",
    difficulty: "MEDIUM",
    tags: ["Array", "Binary Search"],
    examples: [{ input: "[3,4,5,1,2]", output: "1" }],
    constraints: "n == nums.length\n1 <= n <= 5000",
    testCases: [{ input: "3,4,5,1,2", output: "1" }, { input: "4,5,6,7,0,1,2", output: "0" }],
    codeSnippet: { JAVASCRIPT: "function findMin(nums) {\n  // Your code here\n}", PYTHON: "def findMin(nums):\n    pass", JAVA: "class Solution {\n    public int findMin(int[] nums) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function findMin(nums) {\n  let left = 0, right = nums.length - 1;\n  while (left < right) {\n    const mid = Math.floor((left + right) / 2);\n    if (nums[mid] > nums[right]) left = mid + 1;\n    else right = mid;\n  }\n  return nums[left];\n}", PYTHON: "def findMin(nums):\n    left, right = 0, len(nums) - 1\n    while left < right:\n        mid = (left + right) // 2\n        if nums[mid] > nums[right]: left = mid + 1\n        else: right = mid\n    return nums[left]", JAVA: "class Solution {\n    public int findMin(int[] nums) {\n        int left = 0, right = nums.length - 1;\n        while (left < right) {\n            int mid = left + (right - left) / 2;\n            if (nums[mid] > nums[right]) left = mid + 1;\n            else right = mid;\n        }\n        return nums[left];\n    }\n}" }
  },
  {
    title: "Koko Eating Bananas",
    description: "Koko loves to eat bananas. There are n piles of bananas, the ith pile has piles[i] bananas. The guards have gone and will come back in h hours.\n\nKoko can decide her bananas-per-hour eating speed of k. Each hour, she chooses some pile of bananas and eats k bananas from that pile.\n\nReturn the minimum integer k such that she can eat all the bananas within h hours.",
    difficulty: "MEDIUM",
    tags: ["Array", "Binary Search"],
    examples: [{ input: "piles = [3,6,7,11], h = 8", output: "4" }],
    constraints: "1 <= piles.length <= 10^4\npiles.length <= h <= 10^9\n1 <= piles[i] <= 10^9",
    testCases: [{ input: "3,6,7,11\n8", output: "4" }, { input: "30,11,23,4,20\n5", output: "30" }],
    codeSnippet: { JAVASCRIPT: "function minEatingSpeed(piles, h) {\n  // Your code here\n}", PYTHON: "def minEatingSpeed(piles, h):\n    pass", JAVA: "class Solution {\n    public int minEatingSpeed(int[] piles, int h) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function minEatingSpeed(piles, h) {\n  let left = 1, right = Math.max(...piles);\n  while (left < right) {\n    const mid = Math.floor((left + right) / 2);\n    const hours = piles.reduce((sum, p) => sum + Math.ceil(p / mid), 0);\n    if (hours <= h) right = mid;\n    else left = mid + 1;\n  }\n  return left;\n}", PYTHON: "def minEatingSpeed(piles, h):\n    import math\n    left, right = 1, max(piles)\n    while left < right:\n        mid = (left + right) // 2\n        hours = sum(math.ceil(p / mid) for p in piles)\n        if hours <= h: right = mid\n        else: left = mid + 1\n    return left", JAVA: "class Solution {\n    public int minEatingSpeed(int[] piles, int h) {\n        int left = 1, right = Arrays.stream(piles).max().getAsInt();\n        while (left < right) {\n            int mid = left + (right - left) / 2;\n            int hours = 0;\n            for (int p : piles) hours += (p + mid - 1) / mid;\n            if (hours <= h) right = mid;\n            else left = mid + 1;\n        }\n        return left;\n    }\n}" }
  },
  {
    title: "Kth Largest Element in an Array",
    description: "Given an integer array nums and an integer k, return the kth largest element in the array.\n\nNote that it is the kth largest element in the sorted order, not the kth distinct element.",
    difficulty: "MEDIUM",
    tags: ["Array", "Divide and Conquer", "Sorting", "Heap", "Quickselect"],
    examples: [{ input: "nums = [3,2,1,5,6,4], k = 2", output: "5" }],
    constraints: "1 <= k <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4",
    testCases: [{ input: "3,2,1,5,6,4\n2", output: "5" }, { input: "3,2,3,1,2,4,5,5,6\n4", output: "4" }],
    codeSnippet: { JAVASCRIPT: "function findKthLargest(nums, k) {\n  // Your code here\n}", PYTHON: "def findKthLargest(nums, k):\n    pass", JAVA: "class Solution {\n    public int findKthLargest(int[] nums, int k) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function findKthLargest(nums, k) {\n  return nums.sort((a, b) => b - a)[k - 1];\n}", PYTHON: "def findKthLargest(nums, k):\n    nums.sort(reverse=True)\n    return nums[k - 1]", JAVA: "class Solution {\n    public int findKthLargest(int[] nums, int k) {\n        Arrays.sort(nums);\n        return nums[nums.length - k];\n    }\n}" }
  },
  {
    title: "Task Scheduler",
    description: "You are given an array of CPU tasks, each represented by letters A to Z, and a cooling time, n. Each cycle or interval allows the completion of one task. Tasks can be completed in any order, but there's a constraint: identical tasks must be separated by at least n intervals due to cooling time.\n\nReturn the minimum number of intervals required to complete all tasks.",
    difficulty: "MEDIUM",
    tags: ["Array", "Hash Table", "Greedy", "Sorting", "Heap", "Counting"],
    examples: [{ input: 'tasks = ["A","A","A","B","B","B"], n = 2', output: "8" }],
    constraints: "1 <= tasks.length <= 10^4\ntasks[i] is an uppercase English letter.\n0 <= n <= 100",
    testCases: [{ input: "A,A,A,B,B,B\n2", output: "8" }, { input: "A,A,A,B,B,B\n0", output: "6" }],
    codeSnippet: { JAVASCRIPT: "function leastInterval(tasks, n) {\n  // Your code here\n}", PYTHON: "def leastInterval(tasks, n):\n    pass", JAVA: "class Solution {\n    public int leastInterval(char[] tasks, int n) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function leastInterval(tasks, n) {\n  const count = {};\n  for (let t of tasks) count[t] = (count[t] || 0) + 1;\n  const maxCount = Math.max(...Object.values(count));\n  const maxCountTasks = Object.values(count).filter(c => c === maxCount).length;\n  return Math.max(tasks.length, (maxCount - 1) * (n + 1) + maxCountTasks);\n}", PYTHON: "def leastInterval(tasks, n):\n    from collections import Counter\n    count = Counter(tasks)\n    max_count = max(count.values())\n    max_count_tasks = sum(1 for c in count.values() if c == max_count)\n    return max(len(tasks), (max_count - 1) * (n + 1) + max_count_tasks)", JAVA: "class Solution {\n    public int leastInterval(char[] tasks, int n) {\n        int[] count = new int[26];\n        for (char t : tasks) count[t - 'A']++;\n        int maxCount = Arrays.stream(count).max().getAsInt();\n        int maxCountTasks = (int) Arrays.stream(count).filter(c -> c == maxCount).count();\n        return Math.max(tasks.length, (maxCount - 1) * (n + 1) + maxCountTasks);\n    }\n}" }
  },
  {
    title: "Design Twitter",
    description: "Design a simplified version of Twitter where users can post tweets, follow/unfollow another user, and see the 10 most recent tweets in the user's news feed.\n\nImplement the Twitter class.",
    difficulty: "MEDIUM",
    tags: ["Hash Table", "Linked List", "Design", "Heap"],
    examples: [{ input: "Twitter operations", output: "News feed" }],
    constraints: "1 <= userId, followerId, followeeId <= 500\n0 <= tweetId <= 10^4",
    testCases: [{ input: "postTweet,1,5;getNewsFeed,1;follow,1,2;postTweet,2,6;getNewsFeed,1", output: "5;6,5" }],
    codeSnippet: { JAVASCRIPT: "class Twitter {\n  constructor() {}\n  postTweet(userId, tweetId) {}\n  getNewsFeed(userId) {}\n  follow(followerId, followeeId) {}\n  unfollow(followerId, followeeId) {}\n}", PYTHON: "class Twitter:\n    def __init__(self): pass\n    def postTweet(self, userId, tweetId): pass\n    def getNewsFeed(self, userId): pass\n    def follow(self, followerId, followeeId): pass\n    def unfollow(self, followerId, followeeId): pass", JAVA: "class Twitter {\n    public Twitter() {}\n    public void postTweet(int userId, int tweetId) {}\n    public List<Integer> getNewsFeed(int userId) {}\n    public void follow(int followerId, int followeeId) {}\n    public void unfollow(int followerId, int followeeId) {}\n}" },
    referenceSolution: { JAVASCRIPT: "class Twitter {\n  constructor() {\n    this.tweets = [];\n    this.following = new Map();\n  }\n  postTweet(userId, tweetId) {\n    this.tweets.push({ userId, tweetId });\n  }\n  getNewsFeed(userId) {\n    const follows = this.following.get(userId) || new Set();\n    follows.add(userId);\n    return this.tweets.filter(t => follows.has(t.userId)).slice(-10).reverse().map(t => t.tweetId);\n  }\n  follow(followerId, followeeId) {\n    if (!this.following.has(followerId)) this.following.set(followerId, new Set());\n    this.following.get(followerId).add(followeeId);\n  }\n  unfollow(followerId, followeeId) {\n    if (this.following.has(followerId)) this.following.get(followerId).delete(followeeId);\n  }\n}", PYTHON: "class Twitter:\n    def __init__(self):\n        self.tweets = []\n        self.following = {}\n    def postTweet(self, userId, tweetId):\n        self.tweets.append((userId, tweetId))\n    def getNewsFeed(self, userId):\n        follows = self.following.get(userId, set()) | {userId}\n        return [t[1] for t in self.tweets[::-1] if t[0] in follows][:10]\n    def follow(self, followerId, followeeId):\n        self.following.setdefault(followerId, set()).add(followeeId)\n    def unfollow(self, followerId, followeeId):\n        if followerId in self.following: self.following[followerId].discard(followeeId)", JAVA: "class Twitter {\n    private List<int[]> tweets = new ArrayList<>();\n    private Map<Integer, Set<Integer>> following = new HashMap<>();\n    public void postTweet(int userId, int tweetId) { tweets.add(new int[]{userId, tweetId}); }\n    public List<Integer> getNewsFeed(int userId) {\n        Set<Integer> follows = following.getOrDefault(userId, new HashSet<>());\n        follows.add(userId);\n        List<Integer> feed = new ArrayList<>();\n        for (int i = tweets.size() - 1; i >= 0 && feed.size() < 10; i--) {\n            if (follows.contains(tweets.get(i)[0])) feed.add(tweets.get(i)[1]);\n        }\n        return feed;\n    }\n    public void follow(int followerId, int followeeId) { following.computeIfAbsent(followerId, k -> new HashSet<>()).add(followeeId); }\n    public void unfollow(int followerId, int followeeId) { if (following.containsKey(followerId)) following.get(followerId).remove(followeeId); }\n}" }
  },
  {
    title: "Subsets",
    description: "Given an integer array nums of unique elements, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Return the solution in any order.",
    difficulty: "MEDIUM",
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    examples: [{ input: "[1,2,3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]" }],
    constraints: "1 <= nums.length <= 10\n-10 <= nums[i] <= 10",
    testCases: [{ input: "1,2,3", output: ";1;2;1,2;3;1,3;2,3;1,2,3" }, { input: "0", output: ";0" }],
    codeSnippet: { JAVASCRIPT: "function subsets(nums) {\n  // Your code here\n}", PYTHON: "def subsets(nums):\n    pass", JAVA: "class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function subsets(nums) {\n  const result = [[]];\n  for (let num of nums) {\n    result.push(...result.map(subset => [...subset, num]));\n  }\n  return result;\n}", PYTHON: "def subsets(nums):\n    result = [[]]\n    for num in nums:\n        result += [subset + [num] for subset in result]\n    return result", JAVA: "class Solution {\n    public List<List<Integer>> subsets(int[] nums) {\n        List<List<Integer>> result = new ArrayList<>();\n        result.add(new ArrayList<>());\n        for (int num : nums) {\n            int size = result.size();\n            for (int i = 0; i < size; i++) {\n                List<Integer> subset = new ArrayList<>(result.get(i));\n                subset.add(num);\n                result.add(subset);\n            }\n        }\n        return result;\n    }\n}" }
  },
  {
    title: "Combination Sum",
    description: "Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order.\n\nThe same number may be chosen from candidates an unlimited number of times.",
    difficulty: "MEDIUM",
    tags: ["Array", "Backtracking"],
    examples: [{ input: "candidates = [2,3,6,7], target = 7", output: "[[2,2,3],[7]]" }],
    constraints: "1 <= candidates.length <= 30\n2 <= candidates[i] <= 40",
    testCases: [{ input: "2,3,6,7\n7", output: "2,2,3;7" }, { input: "2,3,5\n8", output: "2,2,2,2;2,3,3;3,5" }],
    codeSnippet: { JAVASCRIPT: "function combinationSum(candidates, target) {\n  // Your code here\n}", PYTHON: "def combinationSum(candidates, target):\n    pass", JAVA: "class Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function combinationSum(candidates, target) {\n  const result = [];\n  function backtrack(start, remaining, path) {\n    if (remaining === 0) { result.push([...path]); return; }\n    if (remaining < 0) return;\n    for (let i = start; i < candidates.length; i++) {\n      path.push(candidates[i]);\n      backtrack(i, remaining - candidates[i], path);\n      path.pop();\n    }\n  }\n  backtrack(0, target, []);\n  return result;\n}", PYTHON: "def combinationSum(candidates, target):\n    result = []\n    def backtrack(start, remaining, path):\n        if remaining == 0:\n            result.append(path[:])\n            return\n        if remaining < 0: return\n        for i in range(start, len(candidates)):\n            path.append(candidates[i])\n            backtrack(i, remaining - candidates[i], path)\n            path.pop()\n    backtrack(0, target, [])\n    return result", JAVA: "class Solution {\n    public List<List<Integer>> combinationSum(int[] candidates, int target) {\n        List<List<Integer>> result = new ArrayList<>();\n        backtrack(candidates, 0, target, new ArrayList<>(), result);\n        return result;\n    }\n    void backtrack(int[] candidates, int start, int remaining, List<Integer> path, List<List<Integer>> result) {\n        if (remaining == 0) { result.add(new ArrayList<>(path)); return; }\n        if (remaining < 0) return;\n        for (int i = start; i < candidates.length; i++) {\n            path.add(candidates[i]);\n            backtrack(candidates, i, remaining - candidates[i], path, result);\n            path.remove(path.size() - 1);\n        }\n    }\n}" }
  },
  {
    title: "Permutations",
    description: "Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.",
    difficulty: "MEDIUM",
    tags: ["Array", "Backtracking"],
    examples: [{ input: "[1,2,3]", output: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]" }],
    constraints: "1 <= nums.length <= 6\n-10 <= nums[i] <= 10",
    testCases: [{ input: "1,2,3", output: "1,2,3;1,3,2;2,1,3;2,3,1;3,1,2;3,2,1" }, { input: "0,1", output: "0,1;1,0" }],
    codeSnippet: { JAVASCRIPT: "function permute(nums) {\n  // Your code here\n}", PYTHON: "def permute(nums):\n    pass", JAVA: "class Solution {\n    public List<List<Integer>> permute(int[] nums) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function permute(nums) {\n  const result = [];\n  function backtrack(path, remaining) {\n    if (remaining.length === 0) { result.push(path); return; }\n    for (let i = 0; i < remaining.length; i++) {\n      backtrack([...path, remaining[i]], [...remaining.slice(0, i), ...remaining.slice(i + 1)]);\n    }\n  }\n  backtrack([], nums);\n  return result;\n}", PYTHON: "def permute(nums):\n    result = []\n    def backtrack(path, remaining):\n        if not remaining:\n            result.append(path)\n            return\n        for i in range(len(remaining)):\n            backtrack(path + [remaining[i]], remaining[:i] + remaining[i+1:])\n    backtrack([], nums)\n    return result", JAVA: "class Solution {\n    public List<List<Integer>> permute(int[] nums) {\n        List<List<Integer>> result = new ArrayList<>();\n        backtrack(new ArrayList<>(), nums, new boolean[nums.length], result);\n        return result;\n    }\n    void backtrack(List<Integer> path, int[] nums, boolean[] used, List<List<Integer>> result) {\n        if (path.size() == nums.length) { result.add(new ArrayList<>(path)); return; }\n        for (int i = 0; i < nums.length; i++) {\n            if (used[i]) continue;\n            used[i] = true;\n            path.add(nums[i]);\n            backtrack(path, nums, used, result);\n            path.remove(path.size() - 1);\n            used[i] = false;\n        }\n    }\n}" }
  },
  {
    title: "Word Search",
    description: "Given an m x n grid of characters board and a string word, return true if word exists in the grid.\n\nThe word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.",
    difficulty: "MEDIUM",
    tags: ["Array", "Backtracking", "Matrix"],
    examples: [{ input: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"', output: "true" }],
    constraints: "m == board.length\nn = board[i].length\n1 <= m, n <= 6\n1 <= word.length <= 15",
    testCases: [{ input: "A,B,C,E;S,F,C,S;A,D,E,E\nABCCED", output: "true" }, { input: "A,B,C,E;S,F,C,S;A,D,E,E\nSEE", output: "true" }],
    codeSnippet: { JAVASCRIPT: "function exist(board, word) {\n  // Your code here\n}", PYTHON: "def exist(board, word):\n    pass", JAVA: "class Solution {\n    public boolean exist(char[][] board, String word) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function exist(board, word) {\n  const m = board.length, n = board[0].length;\n  function dfs(r, c, idx) {\n    if (idx === word.length) return true;\n    if (r < 0 || r >= m || c < 0 || c >= n || board[r][c] !== word[idx]) return false;\n    const temp = board[r][c];\n    board[r][c] = '#';\n    const found = dfs(r+1, c, idx+1) || dfs(r-1, c, idx+1) || dfs(r, c+1, idx+1) || dfs(r, c-1, idx+1);\n    board[r][c] = temp;\n    return found;\n  }\n  for (let r = 0; r < m; r++) {\n    for (let c = 0; c < n; c++) {\n      if (dfs(r, c, 0)) return true;\n    }\n  }\n  return false;\n}", PYTHON: "def exist(board, word):\n    m, n = len(board), len(board[0])\n    def dfs(r, c, idx):\n        if idx == len(word): return True\n        if r < 0 or r >= m or c < 0 or c >= n or board[r][c] != word[idx]: return False\n        temp, board[r][c] = board[r][c], '#'\n        found = dfs(r+1, c, idx+1) or dfs(r-1, c, idx+1) or dfs(r, c+1, idx+1) or dfs(r, c-1, idx+1)\n        board[r][c] = temp\n        return found\n    return any(dfs(r, c, 0) for r in range(m) for c in range(n))", JAVA: "class Solution {\n    public boolean exist(char[][] board, String word) {\n        int m = board.length, n = board[0].length;\n        for (int r = 0; r < m; r++) {\n            for (int c = 0; c < n; c++) {\n                if (dfs(board, word, r, c, 0)) return true;\n            }\n        }\n        return false;\n    }\n    boolean dfs(char[][] board, String word, int r, int c, int idx) {\n        if (idx == word.length()) return true;\n        if (r < 0 || r >= board.length || c < 0 || c >= board[0].length || board[r][c] != word.charAt(idx)) return false;\n        char temp = board[r][c];\n        board[r][c] = '#';\n        boolean found = dfs(board, word, r+1, c, idx+1) || dfs(board, word, r-1, c, idx+1) || dfs(board, word, r, c+1, idx+1) || dfs(board, word, r, c-1, idx+1);\n        board[r][c] = temp;\n        return found;\n    }\n}" }
  }
];
