// Additional problems - Part 5 (problems 46-55)
export default [
  {
    title: "Lowest Common Ancestor of BST",
    description: "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.\n\nThe lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants.",
    difficulty: "MEDIUM",
    tags: ["Tree", "DFS", "BST", "Binary Tree"],
    examples: [{ input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", output: "6" }],
    constraints: "The number of nodes in the tree is in the range [2, 10^5].\n-10^9 <= Node.val <= 10^9",
    testCases: [{ input: "6,2,8,0,4,7,9,null,null,3,5\n2\n8", output: "6" }, { input: "6,2,8,0,4,7,9,null,null,3,5\n2\n4", output: "2" }],
    codeSnippet: { JAVASCRIPT: "function lowestCommonAncestor(root, p, q) {\n  // Your code here\n}", PYTHON: "def lowestCommonAncestor(root, p, q):\n    pass", JAVA: "class Solution {\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function lowestCommonAncestor(root, p, q) {\n  while (root) {\n    if (p.val < root.val && q.val < root.val) root = root.left;\n    else if (p.val > root.val && q.val > root.val) root = root.right;\n    else return root;\n  }\n}", PYTHON: "def lowestCommonAncestor(root, p, q):\n    while root:\n        if p.val < root.val and q.val < root.val: root = root.left\n        elif p.val > root.val and q.val > root.val: root = root.right\n        else: return root", JAVA: "class Solution {\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n        while (root != null) {\n            if (p.val < root.val && q.val < root.val) root = root.left;\n            else if (p.val > root.val && q.val > root.val) root = root.right;\n            else return root;\n        }\n        return null;\n    }\n}" }
  },
  {
    title: "Validate Binary Search Tree",
    description: "Given the root of a binary tree, determine if it is a valid binary search tree (BST).\n\nA valid BST is defined as follows:\n- The left subtree of a node contains only nodes with keys less than the node's key.\n- The right subtree of a node contains only nodes with keys greater than the node's key.\n- Both the left and right subtrees must also be binary search trees.",
    difficulty: "MEDIUM",
    tags: ["Tree", "DFS", "BST", "Binary Tree"],
    examples: [{ input: "root = [2,1,3]", output: "true" }, { input: "root = [5,1,4,null,null,3,6]", output: "false" }],
    constraints: "The number of nodes in the tree is in the range [1, 10^4].\n-2^31 <= Node.val <= 2^31 - 1",
    testCases: [{ input: "2,1,3", output: "true" }, { input: "5,1,4,null,null,3,6", output: "false" }],
    codeSnippet: { JAVASCRIPT: "function isValidBST(root) {\n  // Your code here\n}", PYTHON: "def isValidBST(root):\n    pass", JAVA: "class Solution {\n    public boolean isValidBST(TreeNode root) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function isValidBST(root, min = -Infinity, max = Infinity) {\n  if (!root) return true;\n  if (root.val <= min || root.val >= max) return false;\n  return isValidBST(root.left, min, root.val) && isValidBST(root.right, root.val, max);\n}", PYTHON: "def isValidBST(root, min_val=float('-inf'), max_val=float('inf')):\n    if not root: return True\n    if root.val <= min_val or root.val >= max_val: return False\n    return isValidBST(root.left, min_val, root.val) and isValidBST(root.right, root.val, max_val)", JAVA: "class Solution {\n    public boolean isValidBST(TreeNode root) {\n        return isValid(root, Long.MIN_VALUE, Long.MAX_VALUE);\n    }\n    boolean isValid(TreeNode node, long min, long max) {\n        if (node == null) return true;\n        if (node.val <= min || node.val >= max) return false;\n        return isValid(node.left, min, node.val) && isValid(node.right, node.val, max);\n    }\n}" }
  },
  {
    title: "Kth Smallest Element in a BST",
    description: "Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.",
    difficulty: "MEDIUM",
    tags: ["Tree", "DFS", "BST", "Binary Tree"],
    examples: [{ input: "root = [3,1,4,null,2], k = 1", output: "1" }],
    constraints: "The number of nodes in the tree is n.\n1 <= k <= n <= 10^4",
    testCases: [{ input: "3,1,4,null,2\n1", output: "1" }, { input: "5,3,6,2,4,null,null,1\n3", output: "3" }],
    codeSnippet: { JAVASCRIPT: "function kthSmallest(root, k) {\n  // Your code here\n}", PYTHON: "def kthSmallest(root, k):\n    pass", JAVA: "class Solution {\n    public int kthSmallest(TreeNode root, int k) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function kthSmallest(root, k) {\n  const stack = [];\n  while (root || stack.length) {\n    while (root) { stack.push(root); root = root.left; }\n    root = stack.pop();\n    if (--k === 0) return root.val;\n    root = root.right;\n  }\n}", PYTHON: "def kthSmallest(root, k):\n    stack = []\n    while root or stack:\n        while root:\n            stack.append(root)\n            root = root.left\n        root = stack.pop()\n        k -= 1\n        if k == 0: return root.val\n        root = root.right", JAVA: "class Solution {\n    public int kthSmallest(TreeNode root, int k) {\n        Stack<TreeNode> stack = new Stack<>();\n        while (root != null || !stack.isEmpty()) {\n            while (root != null) { stack.push(root); root = root.left; }\n            root = stack.pop();\n            if (--k == 0) return root.val;\n            root = root.right;\n        }\n        return -1;\n    }\n}" }
  },
  {
    title: "Binary Tree Level Order Traversal",
    description: "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
    difficulty: "MEDIUM",
    tags: ["Tree", "BFS", "Binary Tree"],
    examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]" }],
    constraints: "The number of nodes in the tree is in the range [0, 2000].\n-1000 <= Node.val <= 1000",
    testCases: [{ input: "3,9,20,null,null,15,7", output: "3;9,20;15,7" }, { input: "1", output: "1" }],
    codeSnippet: { JAVASCRIPT: "function levelOrder(root) {\n  // Your code here\n}", PYTHON: "def levelOrder(root):\n    pass", JAVA: "class Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function levelOrder(root) {\n  if (!root) return [];\n  const result = [], queue = [root];\n  while (queue.length) {\n    const level = [], size = queue.length;\n    for (let i = 0; i < size; i++) {\n      const node = queue.shift();\n      level.push(node.val);\n      if (node.left) queue.push(node.left);\n      if (node.right) queue.push(node.right);\n    }\n    result.push(level);\n  }\n  return result;\n}", PYTHON: "def levelOrder(root):\n    if not root: return []\n    result, queue = [], [root]\n    while queue:\n        level, size = [], len(queue)\n        for _ in range(size):\n            node = queue.pop(0)\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result", JAVA: "class Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n        List<List<Integer>> result = new ArrayList<>();\n        if (root == null) return result;\n        Queue<TreeNode> queue = new LinkedList<>();\n        queue.offer(root);\n        while (!queue.isEmpty()) {\n            List<Integer> level = new ArrayList<>();\n            int size = queue.size();\n            for (int i = 0; i < size; i++) {\n                TreeNode node = queue.poll();\n                level.add(node.val);\n                if (node.left != null) queue.offer(node.left);\n                if (node.right != null) queue.offer(node.right);\n            }\n            result.add(level);\n        }\n        return result;\n    }\n}" }
  },
  {
    title: "Construct Binary Tree from Preorder and Inorder",
    description: "Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.",
    difficulty: "MEDIUM",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    examples: [{ input: "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]", output: "[3,9,20,null,null,15,7]" }],
    constraints: "1 <= preorder.length <= 3000\ninorder.length == preorder.length\npreorder and inorder consist of unique values.",
    testCases: [{ input: "3,9,20,15,7\n9,3,15,20,7", output: "3,9,20,null,null,15,7" }],
    codeSnippet: { JAVASCRIPT: "function buildTree(preorder, inorder) {\n  // Your code here\n}", PYTHON: "def buildTree(preorder, inorder):\n    pass", JAVA: "class Solution {\n    public TreeNode buildTree(int[] preorder, int[] inorder) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function buildTree(preorder, inorder) {\n  if (!preorder.length) return null;\n  const root = { val: preorder[0], left: null, right: null };\n  const mid = inorder.indexOf(preorder[0]);\n  root.left = buildTree(preorder.slice(1, mid + 1), inorder.slice(0, mid));\n  root.right = buildTree(preorder.slice(mid + 1), inorder.slice(mid + 1));\n  return root;\n}", PYTHON: "def buildTree(preorder, inorder):\n    if not preorder: return None\n    root = TreeNode(preorder[0])\n    mid = inorder.index(preorder[0])\n    root.left = buildTree(preorder[1:mid+1], inorder[:mid])\n    root.right = buildTree(preorder[mid+1:], inorder[mid+1:])\n    return root", JAVA: "class Solution {\n    int preIdx = 0;\n    Map<Integer, Integer> inMap = new HashMap<>();\n    public TreeNode buildTree(int[] preorder, int[] inorder) {\n        for (int i = 0; i < inorder.length; i++) inMap.put(inorder[i], i);\n        return build(preorder, 0, inorder.length - 1);\n    }\n    TreeNode build(int[] preorder, int left, int right) {\n        if (left > right) return null;\n        TreeNode root = new TreeNode(preorder[preIdx++]);\n        int mid = inMap.get(root.val);\n        root.left = build(preorder, left, mid - 1);\n        root.right = build(preorder, mid + 1, right);\n        return root;\n    }\n}" }
  },
  {
    title: "Clone Graph",
    description: "Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph.\n\nEach node in the graph contains a value (int) and a list (List[Node]) of its neighbors.",
    difficulty: "MEDIUM",
    tags: ["Hash Table", "DFS", "BFS", "Graph"],
    examples: [{ input: "adjList = [[2,4],[1,3],[2,4],[1,3]]", output: "[[2,4],[1,3],[2,4],[1,3]]" }],
    constraints: "The number of nodes in the graph is in the range [0, 100].\n1 <= Node.val <= 100",
    testCases: [{ input: "2,4;1,3;2,4;1,3", output: "2,4;1,3;2,4;1,3" }],
    codeSnippet: { JAVASCRIPT: "function cloneGraph(node) {\n  // Your code here\n}", PYTHON: "def cloneGraph(node):\n    pass", JAVA: "class Solution {\n    public Node cloneGraph(Node node) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function cloneGraph(node) {\n  if (!node) return null;\n  const visited = new Map();\n  function clone(n) {\n    if (visited.has(n)) return visited.get(n);\n    const copy = { val: n.val, neighbors: [] };\n    visited.set(n, copy);\n    for (let neighbor of n.neighbors) copy.neighbors.push(clone(neighbor));\n    return copy;\n  }\n  return clone(node);\n}", PYTHON: "def cloneGraph(node):\n    if not node: return None\n    visited = {}\n    def clone(n):\n        if n in visited: return visited[n]\n        copy = Node(n.val, [])\n        visited[n] = copy\n        copy.neighbors = [clone(neighbor) for neighbor in n.neighbors]\n        return copy\n    return clone(node)", JAVA: "class Solution {\n    Map<Node, Node> visited = new HashMap<>();\n    public Node cloneGraph(Node node) {\n        if (node == null) return null;\n        if (visited.containsKey(node)) return visited.get(node);\n        Node copy = new Node(node.val, new ArrayList<>());\n        visited.put(node, copy);\n        for (Node neighbor : node.neighbors) copy.neighbors.add(cloneGraph(neighbor));\n        return copy;\n    }\n}" }
  },
  {
    title: "Number of Islands",
    description: "Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.\n\nAn island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.",
    difficulty: "MEDIUM",
    tags: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    examples: [{ input: 'grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', output: "1" }],
    constraints: "m == grid.length\nn == grid[i].length\n1 <= m, n <= 300\ngrid[i][j] is '0' or '1'.",
    testCases: [{ input: "1,1,1,1,0;1,1,0,1,0;1,1,0,0,0;0,0,0,0,0", output: "1" }, { input: "1,1,0,0,0;1,1,0,0,0;0,0,1,0,0;0,0,0,1,1", output: "3" }],
    codeSnippet: { JAVASCRIPT: "function numIslands(grid) {\n  // Your code here\n}", PYTHON: "def numIslands(grid):\n    pass", JAVA: "class Solution {\n    public int numIslands(char[][] grid) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function numIslands(grid) {\n  let count = 0;\n  function dfs(r, c) {\n    if (r < 0 || r >= grid.length || c < 0 || c >= grid[0].length || grid[r][c] === '0') return;\n    grid[r][c] = '0';\n    dfs(r + 1, c); dfs(r - 1, c); dfs(r, c + 1); dfs(r, c - 1);\n  }\n  for (let r = 0; r < grid.length; r++) {\n    for (let c = 0; c < grid[0].length; c++) {\n      if (grid[r][c] === '1') { count++; dfs(r, c); }\n    }\n  }\n  return count;\n}", PYTHON: "def numIslands(grid):\n    count = 0\n    def dfs(r, c):\n        if r < 0 or r >= len(grid) or c < 0 or c >= len(grid[0]) or grid[r][c] == '0': return\n        grid[r][c] = '0'\n        dfs(r + 1, c); dfs(r - 1, c); dfs(r, c + 1); dfs(r, c - 1)\n    for r in range(len(grid)):\n        for c in range(len(grid[0])):\n            if grid[r][c] == '1':\n                count += 1\n                dfs(r, c)\n    return count", JAVA: "class Solution {\n    public int numIslands(char[][] grid) {\n        int count = 0;\n        for (int r = 0; r < grid.length; r++) {\n            for (int c = 0; c < grid[0].length; c++) {\n                if (grid[r][c] == '1') { count++; dfs(grid, r, c); }\n            }\n        }\n        return count;\n    }\n    void dfs(char[][] grid, int r, int c) {\n        if (r < 0 || r >= grid.length || c < 0 || c >= grid[0].length || grid[r][c] == '0') return;\n        grid[r][c] = '0';\n        dfs(grid, r + 1, c); dfs(grid, r - 1, c); dfs(grid, r, c + 1); dfs(grid, r, c - 1);\n    }\n}" }
  },
  {
    title: "Pacific Atlantic Water Flow",
    description: "There is an m x n rectangular island that borders both the Pacific Ocean and Atlantic Ocean. The Pacific Ocean touches the island's left and top edges, and the Atlantic Ocean touches the island's right and bottom edges.\n\nReturn a 2D list of grid coordinates result where result[i] = [ri, ci] denotes that rain water can flow from cell (ri, ci) to both the Pacific and Atlantic oceans.",
    difficulty: "MEDIUM",
    tags: ["Array", "DFS", "BFS", "Matrix"],
    examples: [{ input: "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", output: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]" }],
    constraints: "m == heights.length\nn == heights[r].length\n1 <= m, n <= 200",
    testCases: [{ input: "1,2,2,3,5;3,2,3,4,4;2,4,5,3,1;6,7,1,4,5;5,1,1,2,4", output: "0,4;1,3;1,4;2,2;3,0;3,1;4,0" }],
    codeSnippet: { JAVASCRIPT: "function pacificAtlantic(heights) {\n  // Your code here\n}", PYTHON: "def pacificAtlantic(heights):\n    pass", JAVA: "class Solution {\n    public List<List<Integer>> pacificAtlantic(int[][] heights) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function pacificAtlantic(heights) {\n  const m = heights.length, n = heights[0].length;\n  const pacific = Array(m).fill(0).map(() => Array(n).fill(false));\n  const atlantic = Array(m).fill(0).map(() => Array(n).fill(false));\n  function dfs(r, c, ocean, prevHeight) {\n    if (r < 0 || r >= m || c < 0 || c >= n || ocean[r][c] || heights[r][c] < prevHeight) return;\n    ocean[r][c] = true;\n    dfs(r + 1, c, ocean, heights[r][c]);\n    dfs(r - 1, c, ocean, heights[r][c]);\n    dfs(r, c + 1, ocean, heights[r][c]);\n    dfs(r, c - 1, ocean, heights[r][c]);\n  }\n  for (let c = 0; c < n; c++) { dfs(0, c, pacific, 0); dfs(m - 1, c, atlantic, 0); }\n  for (let r = 0; r < m; r++) { dfs(r, 0, pacific, 0); dfs(r, n - 1, atlantic, 0); }\n  const result = [];\n  for (let r = 0; r < m; r++) {\n    for (let c = 0; c < n; c++) {\n      if (pacific[r][c] && atlantic[r][c]) result.push([r, c]);\n    }\n  }\n  return result;\n}", PYTHON: "def pacificAtlantic(heights):\n    m, n = len(heights), len(heights[0])\n    pacific, atlantic = set(), set()\n    def dfs(r, c, ocean, prev_height):\n        if r < 0 or r >= m or c < 0 or c >= n or (r, c) in ocean or heights[r][c] < prev_height: return\n        ocean.add((r, c))\n        for dr, dc in [(1, 0), (-1, 0), (0, 1), (0, -1)]: dfs(r + dr, c + dc, ocean, heights[r][c])\n    for c in range(n): dfs(0, c, pacific, 0); dfs(m - 1, c, atlantic, 0)\n    for r in range(m): dfs(r, 0, pacific, 0); dfs(r, n - 1, atlantic, 0)\n    return list(pacific & atlantic)", JAVA: "class Solution {\n    int[][] directions = {{1,0},{-1,0},{0,1},{0,-1}};\n    public List<List<Integer>> pacificAtlantic(int[][] heights) {\n        int m = heights.length, n = heights[0].length;\n        boolean[][] pacific = new boolean[m][n], atlantic = new boolean[m][n];\n        for (int c = 0; c < n; c++) { dfs(heights, 0, c, pacific, 0); dfs(heights, m-1, c, atlantic, 0); }\n        for (int r = 0; r < m; r++) { dfs(heights, r, 0, pacific, 0); dfs(heights, r, n-1, atlantic, 0); }\n        List<List<Integer>> result = new ArrayList<>();\n        for (int r = 0; r < m; r++) for (int c = 0; c < n; c++) if (pacific[r][c] && atlantic[r][c]) result.add(Arrays.asList(r, c));\n        return result;\n    }\n    void dfs(int[][] heights, int r, int c, boolean[][] ocean, int prev) {\n        if (r < 0 || r >= heights.length || c < 0 || c >= heights[0].length || ocean[r][c] || heights[r][c] < prev) return;\n        ocean[r][c] = true;\n        for (int[] d : directions) dfs(heights, r + d[0], c + d[1], ocean, heights[r][c]);\n    }\n}" }
  },
  {
    title: "Course Schedule",
    description: "There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.\n\nReturn true if you can finish all courses. Otherwise, return false.",
    difficulty: "MEDIUM",
    tags: ["DFS", "BFS", "Graph", "Topological Sort"],
    examples: [{ input: "numCourses = 2, prerequisites = [[1,0]]", output: "true" }],
    constraints: "1 <= numCourses <= 2000\n0 <= prerequisites.length <= 5000",
    testCases: [{ input: "2\n1,0", output: "true" }, { input: "2\n1,0;0,1", output: "false" }],
    codeSnippet: { JAVASCRIPT: "function canFinish(numCourses, prerequisites) {\n  // Your code here\n}", PYTHON: "def canFinish(numCourses, prerequisites):\n    pass", JAVA: "class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function canFinish(numCourses, prerequisites) {\n  const graph = Array(numCourses).fill(0).map(() => []);\n  const visited = Array(numCourses).fill(0);\n  for (let [a, b] of prerequisites) graph[b].push(a);\n  function hasCycle(node) {\n    if (visited[node] === 1) return true;\n    if (visited[node] === 2) return false;\n    visited[node] = 1;\n    for (let neighbor of graph[node]) if (hasCycle(neighbor)) return true;\n    visited[node] = 2;\n    return false;\n  }\n  for (let i = 0; i < numCourses; i++) if (hasCycle(i)) return false;\n  return true;\n}", PYTHON: "def canFinish(numCourses, prerequisites):\n    graph = [[] for _ in range(numCourses)]\n    visited = [0] * numCourses\n    for a, b in prerequisites: graph[b].append(a)\n    def hasCycle(node):\n        if visited[node] == 1: return True\n        if visited[node] == 2: return False\n        visited[node] = 1\n        for neighbor in graph[node]:\n            if hasCycle(neighbor): return True\n        visited[node] = 2\n        return False\n    return not any(hasCycle(i) for i in range(numCourses))", JAVA: "class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        List<List<Integer>> graph = new ArrayList<>();\n        for (int i = 0; i < numCourses; i++) graph.add(new ArrayList<>());\n        int[] visited = new int[numCourses];\n        for (int[] p : prerequisites) graph.get(p[1]).add(p[0]);\n        for (int i = 0; i < numCourses; i++) if (hasCycle(graph, visited, i)) return false;\n        return true;\n    }\n    boolean hasCycle(List<List<Integer>> graph, int[] visited, int node) {\n        if (visited[node] == 1) return true;\n        if (visited[node] == 2) return false;\n        visited[node] = 1;\n        for (int neighbor : graph.get(node)) if (hasCycle(graph, visited, neighbor)) return true;\n        visited[node] = 2;\n        return false;\n    }\n}" }
  },
  {
    title: "Coin Change",
    description: "You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.\n\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.",
    difficulty: "MEDIUM",
    tags: ["Array", "Dynamic Programming", "BFS"],
    examples: [{ input: "coins = [1,2,5], amount = 11", output: "3", explanation: "11 = 5 + 5 + 1" }],
    constraints: "1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4",
    testCases: [{ input: "1,2,5\n11", output: "3" }, { input: "2\n3", output: "-1" }, { input: "1\n0", output: "0" }],
    codeSnippet: { JAVASCRIPT: "function coinChange(coins, amount) {\n  // Your code here\n}", PYTHON: "def coinChange(coins, amount):\n    pass", JAVA: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function coinChange(coins, amount) {\n  const dp = Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (let i = 1; i <= amount; i++) {\n    for (let coin of coins) {\n      if (coin <= i) dp[i] = Math.min(dp[i], dp[i - coin] + 1);\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}", PYTHON: "def coinChange(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for coin in coins:\n            if coin <= i: dp[i] = min(dp[i], dp[i - coin] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1", JAVA: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n        int[] dp = new int[amount + 1];\n        Arrays.fill(dp, amount + 1);\n        dp[0] = 0;\n        for (int i = 1; i <= amount; i++) {\n            for (int coin : coins) {\n                if (coin <= i) dp[i] = Math.min(dp[i], dp[i - coin] + 1);\n            }\n        }\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n}" }
  },
  {
    title: "House Robber",
    description: "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected.\n\nGiven an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.",
    difficulty: "MEDIUM",
    tags: ["Array", "Dynamic Programming"],
    examples: [{ input: "[1,2,3,1]", output: "4", explanation: "Rob house 1 and 3" }, { input: "[2,7,9,3,1]", output: "12" }],
    constraints: "1 <= nums.length <= 100\n0 <= nums[i] <= 400",
    testCases: [{ input: "1,2,3,1", output: "4" }, { input: "2,7,9,3,1", output: "12" }],
    codeSnippet: { JAVASCRIPT: "function rob(nums) {\n  // Your code here\n}", PYTHON: "def rob(nums):\n    pass", JAVA: "class Solution {\n    public int rob(int[] nums) {\n    }\n}" },
    referenceSolution: { JAVASCRIPT: "function rob(nums) {\n  let prev2 = 0, prev1 = 0;\n  for (let num of nums) {\n    const temp = Math.max(prev1, prev2 + num);\n    prev2 = prev1;\n    prev1 = temp;\n  }\n  return prev1;\n}", PYTHON: "def rob(nums):\n    prev2 = prev1 = 0\n    for num in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + num)\n    return prev1", JAVA: "class Solution {\n    public int rob(int[] nums) {\n        int prev2 = 0, prev1 = 0;\n        for (int num : nums) {\n            int temp = Math.max(prev1, prev2 + num);\n            prev2 = prev1;\n            prev1 = temp;\n        }\n        return prev1;\n    }\n}" }
  }
];
