services:
  - type: web
    name: leetlab-backend
    env: node
    region: oregon
    plan: starter
    rootDir: .
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: leetlab-backend
          property: host
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_BASE_URL
        sync: false
      - key: RAPIDAPI_HOST
        sync: false
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_AUTH
        sync: false
      - key: COOKIE_DOMAIN
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
